// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type GroupPermission struct {
	GroupID      int32 `db:"group_id" json:"group_id"`
	PermissionID int32 `db:"permission_id" json:"permission_id"`
}

type Permission struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type User struct {
	ID           int32              `db:"id" json:"id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Email        string             `db:"email" json:"email"`
}

type UserGroup struct {
	UserID  int32 `db:"user_id" json:"user_id"`
	GroupID int32 `db:"group_id" json:"group_id"`
}
